# ui/texts.py
"""
Módulo de internacionalização (i18n) da interface do usuário.

Este módulo contém o dicionário TEXTS com todas as strings da interface
traduzidas para Português (pt) e Inglês (en). O idioma é selecionado
dinamicamente pelo usuário na interface Streamlit.

As chaves do dicionário são consistentes entre os idiomas para permitir
troca fácil de linguagem em runtime.

Categorias de textos:
- Labels de UI (botões, títulos, placeholders)
- Mensagens de status (processando, erro, sucesso)
- Títulos de seções (Ishikawa, 5 Porquês, etc.)
- Métricas de tokens (entrada, saída, custo)
"""

TEXTS = {
    "pt": {
        "title": "Análise de Falhas",
        "api_key_label": "🔑 Chave da API:",
        "folder_label": "📁 Caminho da pasta raiz:",
        "folder_instruction": "Cole o caminho da pasta raiz do Windows Explorer...",
        "run_button": "🚀 Executar Análise",
        "processing": "⏳ Processando...",
        "no_api_key": "❌ Por favor, forneça a chave da API do Gemini.",
        "no_folder": "❌ Por favor, insira o caminho da pasta raiz.",
        "folder_not_found": "❌ A pasta '{}' não foi encontrada.",
        "success": "✅ Análise concluída. Relatórios gerados em 'relatorios/'.",
        "excel_data": "📊 Dados do Excel",
        "image_analysis": "🖼️ Análise de Imagens",
        "raw_response": "🤖 Resposta Bruta",
        "equipment": "Equipamento",
        "area": "Área",
        "subgroup": "Subgrupo",
        "description": "Descrição do problema",
        "folder": "Pasta",
        "download_button": "📥 Baixar Resultado",
        "root_path_input": "📁 Caminho:",
        "ishikawa_expander": "📊 Diagrama de Ishikawa",
        "five_whys_expander": "🔍 5 Porquês",
        "video_disabled": "🎥 Análise de vídeo desabilitada",
        "image_disabled": "🖼️ Análise de imagem desabilitada",
        "total_items": "📊 {total} item(ns) a serem analisados entre Excel, imagens e vídeos.",
        "processing_folder": "📂 Processando pasta: {folder}",
        "video_disabled_ui": "🎥 Habilitar analise de Video",
        "image_disabled_ui": "🖼️ Habilitar analise de Imagem",
        "token_ok": "✅ Quantidade de informações adequada para análise.",
        "token_exceeded": "⚠️ O prompt excedeu o limite ideal de 30.000 tokens. Considere reduzir a quantidade de mídias.",
        "token_section": "📏 Tokens",
        "token_used": "📏 Tokens usados no prompt:",
        "video_analysis_title": "🎥 Análise de Vídeo",
        "ishikawa_title": "📊 Diagrama de Ishikawa",
        "no_five_whys": "🚫 Nenhuma análise fornecida / No analysis provided",
        "five_whys_title": "**🔍 5 Porquês",
        "no_raw_response": "Nenhuma resposta bruta disponível",
        "no_video_found": "Nenhuma análise de vídeo encontrada",
        "ishikawa_effect": "EFEITO",
        "history_expander": "📖 Histórico Correlacionado pela IA",
        "images": "Imagens",
        "videos": "Vídeos",
        "media_context_label": "Contexto",
        "history_searching": "Buscando histórico de falhas para: {folder_name}...",
        "history_refining": "Refinando {count} falhas históricas com IA...",
        "generating_rca": "🧠 Gerando análise RCA final para: {folder_name}...",
        "analysis_complete": "✅ Análise concluída com sucesso!",
        "media_context_header": "Contexto Adicional (Opcional)",
        "media_context_instruction": "Adicione observações específicas para guiar a análise da IA em cada mídia.",
        "token_media": "🖼️ Tokens das Mídias:",
        "token_history": "📖 Tokens do Histórico Refinado:",
        "token_prompt": "🎯 Tokens do Prompt Final:",
        "token_total": "🧮 Total de Tokens:",
        "response_tokens": "🗳️ Tokens de Resposta:",
        "history_input_tokens": "📤 Tokens de Entrada no Histórico:",
        "history_output_tokens": "📥 Tokens de Saída do Histórico:",
        "analysis_cost": "💵 Custo desta análise:",
        "tokens_title_md": "📏 Tokens da Análise Final",
        "tokens_used_md": "Tokens usados no prompt final",
        "broad_history_expander": "📚 Histórico Bruto Encontrado ({count} registros)", 
        "historical_analysis_title": "#### Análise Histórica {index}",
        "tokens_input": "🔢 Tokens de Entrada (Input):", 
        "tokens_output": "📤 Tokens de Saída (Output):" ,
        "correlation_title_md": "📚 Correlação com Histórico de Falhas",
        "reading_excel": "Lendo Excel em: {folder_name}",
        "analyzing_videos": "Analisando {count} vídeo(s) em: {folder_name}",
        "analyzing_images": "Analisando {count} imagem(ns) em: {folder_name}",
        "conclusion_expander": "🎯 Conclusão Final",
        "conclusion_title": "Conclusão da Análise",
        "no_conclusion": "Nenhuma conclusão disponível",
    },
    "en": {
        "title": "Failure Analysis",
        "api_key_label": "🔑 API Key:",
        "folder_label": "📁 Root folder path:",
        "folder_instruction": "Paste the root folder path from Windows Explorer...",
        "run_button": "🚀 Run Analysis",
        "processing": "⏳ Processing...",
        "no_api_key": "❌ Please provide the Gemini API key.",
        "no_folder": "❌ Please enter the root folder path.",
        "folder_not_found": "❌ The folder '{}' was not found.",
        "success": "✅ Analysis completed. Reports generated in 'relatorios/'.",
        "excel_data": "📊 Excel Data",
        "image_analysis": "🖼️ Image Analysis",
        "raw_response": "🤖 Raw Response",
        "equipment": "Equipment",
        "area": "Area",
        "subgroup": "Subgroup",
        "description": "Problem description",
        "folder": "Folder",
        "download_button": "📥 Download Result",
        "root_path_input": "📁 Path:",
        "ishikawa_expander": "📊 Ishikawa Diagram",
        "five_whys_expander": "🔍 5 Whys",
        "video_disabled": "🎥 Video analysis disabled",
        "image_disabled": "🖼️ Image analysis disabled",
        "total_items": "📊 {total} item(s) to be analyzed including Excel, images and videos.",
        "processing_folder": "📂 Processing folder: {folder}",
        "video_disabled_ui": "🎥 Enable Video analysis",
        "image_disabled_ui": "🖼️ Enable Image analysis ",
        "token_ok": "✅ An appropriate amount of information for analysis.",
        "token_exceeded": "⚠️ The prompt exceeded the ideal limit of 30,000 tokens. Consider reducing the amount of media.",
        "token_section": "📏 Tokens",
        "token_used": "📏 Tokens used in prompt:",
        "video_analysis_title": "🎥 Video Analysis",
        "ishikawa_title": "📊 Ishikawa Diagram",
        "no_five_whys": "🚫 No analysis provided",
        "five_whys_title": "**🔍 5 Whys**",
        "no_raw_response": "No raw response available",
        "no_video_found": "No video analysis found",
        "ishikawa_effect": "EFFECT",
        "history_expander": "📖 AI-Correlated History",
        "images": "Images",
        "videos": "Videos",
        "media_context_label": "Context",
        "history_searching": "Searching failure history for: {folder_name}...",
        "history_refining": "Refining {count} historical failures with AI...",
        "generating_rca": "🧠 Generating final RCA analysis for: {folder_name}...",
        "analysis_complete": "✅ Analysis completed successfully!",
        "media_context_header": "Additional Context (Optional)",
        "media_context_instruction": "Add specific observations to guide the AI's analysis for each media file.",
        "token_media": "🖼️ Media Tokens:",
        "token_history": "📖 Refined History Tokens:",
        "token_prompt": "🎯 Final Prompt Tokens:",
        "token_total": "🧮 Total Tokens:",
        "response_tokens": "🗳️ Response Tokens:",
        "history_input_tokens": "📤 History Input Tokens:",
        "history_output_tokens": "📥 History Output Tokens:",
        "token_total": "🔢 Total Tokens:",
        "analysis_cost": "💵 Cost of this analysis:",
        "tokens_title_md": "📏 Final Analysis Tokens", 
        "tokens_used_md": "Tokens used in the final prompt",
        "broad_history_expander": "📚 Raw History Found ({count} records)", 
        "historical_analysis_title": "#### Historical Analysis {index}",
         "tokens_input": "🔢 Input Tokens:", 
        "tokens_output": "📤 Output Tokens:" ,
        "correlation_title_md": "📚 Failure History Correlation",
        "reading_excel": "Reading Excel in: {folder_name}",
        "analyzing_videos": "Analyzing {count} video(s) in: {folder_name}",
        "analyzing_images": "Analyzing {count} image(s) in: {folder_name}",
        "ai_correlation_header": "🔍 AI Correlation Analysis",
        "correlated_failure_title": "Correlated Failure",
        "description_of_failure": "📝 Failure Description:",
        "relevance_technical": "🎯 Technical Relevance:",
        "relevant_data": "📋 Relevant Data:",
        "action_plan_defined": "🔧 Defined Action Plan:",
        "conclusion_expander": "🎯 Final Conclusion",
        "conclusion_title": "Analysis Conclusion",
        "no_conclusion": "No conclusion available",
    }
}
