# ui/texts.py

TEXTS = {
    "pt": {
        "title": "Análise de Falhas",
        "api_key_label": "🔑 Chave da API:",
        "folder_label": "📁 Caminho da pasta raiz:",
        "folder_instruction": "Cole o caminho da pasta raiz do Windows Explorer...",
        "run_button": "🚀 Executar Análise",
        "processing": "⏳ Processando...",
        "no_api_key": "❌ Por favor, forneça a chave da API do Gemini.",
        "no_folder": "❌ Por favor, insira o caminho da pasta raiz.",
        "folder_not_found": "❌ A pasta '{}' não foi encontrada.",
        "success": "✅ Análise concluída. Relatórios gerados em 'relatorios/'.",
        "excel_data": "📊 Dados do Excel",
        "image_analysis": "🖼️ Análise de Imagens",
        "raw_response": "🤖 Resposta Bruta",
        "equipment": "Equipamento",
        "area": "Área",
        "subgroup": "Subgrupo",
        "description": "Descrição do problema",
        "folder": "Pasta",
        "download_button": "📥 Baixar Resultado",
        "root_path_input": "📁 Caminho:",
        "ishikawa_expander": "📊 Diagrama de Ishikawa",
        "five_whys_expander": "🔍 5 Porquês",
        "video_disabled": "🎥 Análise de vídeo desabilitada",
        "image_disabled": "🖼️ Análise de imagem desabilitada",
        "total_items": "📊 {total} item(ns) a serem analisados entre Excel, imagens e vídeos.",
        "processing_folder": "📂 Processando pasta: {folder}",
        "video_disabled_ui": "🎥 Habilitar analise de Video",
        "image_disabled_ui": "🖼️ Habilitar analise de Imagem",
        "token_ok": "✅ Quantidade de informações adequada para análise.",
        "token_exceeded": "⚠️ O prompt excedeu o limite ideal de 30.000 tokens. Considere reduzir a quantidade de mídias.",
        "token_section": "📏 Tokens",
        "token_used": "📏 Tokens usados no prompt:",
        "video_analysis_title": "🎥 Análise de Vídeo",
        "ishikawa_title": "📊 Diagrama de Ishikawa",
        "no_five_whys": "🚫 Nenhuma análise fornecida / No analysis provided",
        "five_whys_title": "**🔍 5 Porquês",
        "no_raw_response": "Nenhuma resposta bruta disponível",
        "no_video_found": "Nenhuma análise de vídeo encontrada",
        "ishikawa_effect": "EFEITO",
        "history_expander": "📖 Histórico Correlacionado pela IA",
        "history_searching": "Buscando histórico de falhas para: {folder_name}...",
        "history_refining": "Refinando {count} falhas históricas com IA...",
        "generating_rca": "Gerando análise de causa raiz para: {folder_name}...",
        "analysis_complete": "Análise concluída! Gerando relatórios...",
        "token_media": "🖼️ Tokens das Mídias:",
        "token_history": "📖 Tokens do Histórico Refinado:",
        "token_prompt": "🎯 Tokens do Prompt Final:",
        "token_total": "🧮 Total de Tokens:",
        "response_tokens": "🗳️ Tokens de Resposta:",
        "history_input_tokens": "📤 Tokens de Entrada no Histórico:",
        "history_output_tokens": "📥 Tokens de Saída do Histórico:",
        "token_total": "🔢 Tokens Totais:",
        "analysis_cost": "💵 Custo desta análise:",
        "tokens_title_md": "📏 Tokens da Análise Final",
        "tokens_used_md": "Tokens usados no prompt final",
        "broad_history_expander": "📚 Histórico Bruto Encontrado ({count} registros)", 
        "historical_analysis_title": "#### Análise Histórica {index}",
        "tokens_input": "🔢 Tokens de Entrada (Input):", 
        "tokens_output": "📤 Tokens de Saída (Output):"  


    },
    "en": {
        "title": "Failure Analysis",
        "api_key_label": "🔑 API Key:",
        "folder_label": "📁 Root folder path:",
        "folder_instruction": "Paste the root folder path from Windows Explorer...",
        "run_button": "🚀 Run Analysis",
        "processing": "⏳ Processing...",
        "no_api_key": "❌ Please provide the Gemini API key.",
        "no_folder": "❌ Please enter the root folder path.",
        "folder_not_found": "❌ The folder '{}' was not found.",
        "success": "✅ Analysis completed. Reports generated in 'relatorios/'.",
        "excel_data": "📊 Excel Data",
        "image_analysis": "🖼️ Image Analysis",
        "raw_response": "🤖 Raw Response",
        "equipment": "Equipment",
        "area": "Area",
        "subgroup": "Subgroup",
        "description": "Problem description",
        "folder": "Folder",
        "download_button": "📥 Download Result",
        "root_path_input": "📁 Path:",
        "ishikawa_expander": "📊 Ishikawa Diagram",
        "five_whys_expander": "🔍 5 Whys",
        "video_disabled": "🎥 Video analysis disabled",
        "image_disabled": "🖼️ Image analysis disabled",
        "total_items": "📊 {total} item(s) to be analyzed including Excel, images and videos.",
        "processing_folder": "📂 Processing folder: {folder}",
        "video_disabled_ui": "🎥 Enable Video analysis",
        "image_disabled_ui": "🖼️ Enable Image analysis ",
        "token_ok": "✅ An appropriate amount of information for analysis.",
        "token_exceeded": "⚠️ The prompt exceeded the ideal limit of 30,000 tokens. Consider reducing the amount of media.",
        "token_section": "📏 Tokens",
        "token_used": "📏 Tokens used in prompt:",
        "video_analysis_title": "🎥 Video Analysis",
        "ishikawa_title": "📊 Ishikawa Diagram",
        "no_five_whys": "🚫 No analysis provided",
        "five_whys_title": "**🔍 5 Whys**",
        "no_raw_response": "No raw response available",
        "no_video_found": "No video analysis found",
        "ishikawa_effect": "EFFECT",
        "history_expander": "📖 AI-Correlated History",
        "history_searching": "Searching failure history for: {folder_name}...",
        "history_refining": "Refining {count} historical failures with AI...",
        "generating_rca": "Generating root cause analysis for: {folder_name}...",
        "analysis_complete": "Analysis complete! Generating reports...",
        "token_media": "🖼️ Media Tokens:",
        "token_history": "📖 Refined History Tokens:",
        "token_prompt": "🎯 Final Prompt Tokens:",
        "token_total": "🧮 Total Tokens:",
        "response_tokens": "🗳️ Response Tokens:",
        "history_input_tokens": "📤 History Input Tokens:",
        "history_output_tokens": "📥 History Output Tokens:",
        "token_total": "🔢 Total Tokens:",
        "analysis_cost": "💵 Cost of this analysis:",
        "tokens_title_md": "📏 Final Analysis Tokens", 
        "tokens_used_md": "Tokens used in the final prompt",
        "broad_history_expander": "📚 Raw History Found ({count} records)", 
        "historical_analysis_title": "#### Historical Analysis {index}",
         "tokens_input": "🔢 Input Tokens:", 
        "tokens_output": "📤 Output Tokens:"  

        
    }
}
